### ISSUE TITLE
Add Merced College to list of Colleges

### ISSUE THREAD

**Issue by adriandarian** [HackMerced/HackMerced-V#10] opened 2020-01-26 06:24 UTC
**Describe the bug**
Merced College is not listed under schools dropdown in the signup page

**To Reproduce**
1. Go to `hackmerced.io`
2. Click on `register`
3. Scroll down to `schools dropdown`
4. See missing college

**Expected behavior**
Merced College should be shown in the list of colleges

**Comment by shiv248** [comment] 2020-01-26 06:42
Merced College is listed in the `universities.js` file. Switching back from web hosted pulling of the University JSON file to hardcode file.

**Comment by adriandarian** [comment] 2020-01-26 07:18
We need to use MLH's list because it was from the MLH packet provided to us. So we can append Merced College to their list in our code. I have already made a PR on MLH's list to add Merced College but do not know when it will get merged. So an append will work for now.

**Comment by shiv248** [comment] 2020-01-27 05:11
the issue is fixed in the new signup page as it implements both the convenience of a selectable list and the ability to add input if it's not listed, while still being searchable. Look into `datalist`.

**Closed as completed by shiv248** 2020-01-27 05:11 UTC
Labels: bug
