### ISSUE TITLE
FAQ design incorrect

### ISSUE THREAD

**Issue by adriandarian** [HackMerced/HackMerced-V#20] opened 2020-01-27 04:33 UTC
**Describe the bug**
FAQ Design is not finished and missing a lot of pieces to make it complete.

**To Reproduce**
1. Go to `develop` branch
2. Change your directory to `client/src/pages/Home`
3. Uncomment the `FAQ` Component and the `import`
4. Run the project locally [Note you only need to run the client not the server]
5. See error

**Expected behavior**
- [ ] Should have a proper accordion layout.
- [ ] Image and FAQs should be aligned in a working CSS Grid layout.
- [ ] There should be a white vertical line in between each question with a white dot at each question

**Screenshots**
![image](https://user-images.githubusercontent.com/23567187/73150232-2c33c700-407a-11ea-9d12-85234b5e96b2.png)

**Additional context**
Temporarily comment out the FAQ on live site until the design is fixed.

**Comment by shiv248** [comment] 2020-01-27 04:52
duplicate of issue #17

**Comment by shiv248** [comment] 2020-01-27 04:52
issue completed and funcitonal on branch `feature/faq`.

**Closed as completed by shiv248** 2020-01-27 04:52 UTC
Labels: bug, duplicate
